### ISSUE TITLE
编辑错误

### ISSUE THREAD

**Issue by surffor2008** [zxh0/jvmgo-book#1]
2.3.2上面strings.HasSuffix(path, ".JAR")后面少一个||符号
2.3.4上面readClass中defer r.Close()是不是应该判断err != nil之前，也就是放在return之前,几个defer都需要调整下位置

**Comment by zxh0** [comment]
你好，感谢你提供反馈。请问你看的是纸书还是电子版呢？
第一个错误我没有找到。我对照纸书第一版，2.3.2小节上面，也就是第12页最下面的代码，是不缺少`||`的。也许是电子版里的错误？
第二个问题，如果`err != nil`，则`r == nil`，所以这样应该是没有问题的。具体可以参考 [Go文档](https://golang.org/pkg/archive/zip/#example_Reader) 里的例子：

``` go
// Open a zip archive for reading.
r, err := zip.OpenReader("testdata/readme.zip")
if err != nil {
    log.Fatal(err)
}
defer r.Close()
```

**Comment by surffor2008** [comment]
我看的是电子版的，第一个有这个问题
感谢指点，第二个问题确实是应该放在这下面，书还在拜读中，orz

**Comment by zxh0** [comment]
是哪里的电子书呢？亚马逊？我好反馈给出版社 ：）

**Comment by surffor2008** [comment]
是百度阅读

**Comment by surffor2008** [comment]
3.2.4 上面的ifmagic连起来了
3.2.5 上面的switchself.majorVersion及case45,case46都连起来了
3.3上面的returnself也连起来了
以上都是来自百度阅读的电子版

**Comment by zxh0** [comment]
好的，再次表示感谢，我会把问题反馈给出版社。

**Comment by cbj07** [comment]
纸质的第一版第三章测试时报错，省略的attr_local_variable_table.go文件和cp_invoke_dynamic.go文件，应在相关小节提醒一下读者。cp_utf8.go文件中如果用简化版的decodeMUTF8函数，会报导入的包未用到，这个是小问题。

**Comment by zxh0** [comment]
@cbj07 感谢提供反馈，我把你的问题复制了一下，创建了一个新的issue，这个先关闭吧。
