### ISSUE TITLE
代码错误

### ISSUE THREAD

**Issue by CURAS** [zxh0/jvmgo-book#10]
第二版194页第二段代码中
`classRef := cp.GetConstant(self.Index).(*rtc.ClassRef)`应该为
`classRef := cp.GetConstant(self.Index).(*heap.ClassRef)`

206页`getField()`函数的声明中的`isStatic`参数缺少类型

不知道新版有没有改正

**Comment by zxh0** [comment]
谢谢，已经登记在勘误表里了。
