### ISSUE TITLE
English version?

### ISSUE THREAD

**Issue by kevindeasis** [zxh0/jvmgo-book#16]
I ran into your repo and your book.
I was wondering if you had any plans of writing the book in english and selling it in amazon because i might be interested in purchasing a copy or 2?
:)

**Comment by zxh0** [comment]
Sorry kevindeasis, I am not able to write this book in English. But I still hope the code in this repo can give you some help.

**Comment by kevindeasis** [comment]
@zxh0 no worries that's fine. Although, I have one last question. Do you have a pdf version of the book that you are selling? Because I would not be able to translate a hard copy of the book, but I might be able to use a translator to translate a pdf copy of the book by copy-pasting it into a translator. Let me know if you do have a copy in PDF or electronic format, because I would like to buy that

**Comment by zxh0** [comment]
@kevindeasis I do not have a pdf copy. You can find the first three chapters from here: https://yuedu.baidu.com/ebook/f9d7b0f4dd36a32d72758138?pn=1&click_type=10010002

**Comment by kevindeasis** [comment]
@zxh0  Alright thanks again for the help

**Comment by zxh0** [comment]
You are welcome @kevindeasis 
And you need some JS trick to copy text from above url : )
