### ISSUE TITLE
书中代码与源码中不符

### ISSUE THREAD

**Issue by imkratos** [zxh0/jvmgo-book#17]
在《自己动手写java虚拟机》中，您的书中194页 anewarray.go 文件中 Execute函数中 `classRef := cp.GetConstant(self.Index).(*rtc.ClassRef)`，而实际应该是`classRef := cp.GetConstant(self.Index).(*heap.ClassRef)` 。不知道我有没有理解错误

**Comment by imkratos** [comment]
另外206页中 getField函数 您的书中少写了 isStatic 的类型bool 哈，代码中也有。

**Comment by zxh0** [comment]
@imkratos 你好， 194页和206页的这两处疏漏已经在之前被其他读者发现了，已经登记在了勘误表里。不过仍然感谢你提供反馈。
