### ISSUE TITLE
37页 常量池大小 图文不符

### ISSUE THREAD

**Issue by JingkaiTang** [zxh0/jvmgo-book#3]
* 第1版第1次印刷
* 第37页 3.3.1 ConstantPool结构体
* 图3-8内容与文字不符

> ClassFileTest的常量池大小是61如图3-8所示

然而图中却是64 -> 00 40
按照第25页上的ClassFileTest代码编译出来class文件的ConstantPool大小确实是64，不过如果去掉主函数上的RuntimeException申明就是61了

**Comment by zxh0** [comment]
收到，多谢 ：）
