### ISSUE TITLE
java版的代码怎么不更新了?

### ISSUE THREAD

**Issue by liangszzz** [zxh0/jvmgo-book#31]

**Comment by zxh0** [comment]
书都印出来了，不能再更新代码了。

**Comment by liangszzz** [comment]
第五章  可以写个java的demo 吗
go的看的 好难懂

**Comment by zxh0** [comment]
@yiyan1992  有问题可以进入这本书的读者群进行讨论

**Comment by liangszzz** [comment]
好吧

**Comment by zxh0** [comment]
@yiyan1992 抱歉，这个问题我之前可能看错了。java版的实现代码，主要是由其他读者提交的。你如果有兴趣，也可以一起维护。
