### ISSUE TITLE
求读者交流群

### ISSUE THREAD

**Issue by KING754** [zxh0/jvmgo-book#40]
求读者交流群

**Comment by zxh0** [comment]
qq: 470333113

**Comment by zxh0** [comment]
@KING754 不好意思，之前脑残了，写错群号了

![WechatIMG161](https://user-images.githubusercontent.com/5507614/100298701-be736700-2fcc-11eb-84b4-d2cb4f2b2493.jpeg)

**Comment by KING754** [comment]
我是说.net,就感觉不对劲了。还以为是你个人的QQ，所以也加了一下。
