### ISSUE TITLE
mac jre路径不识别

### ISSUE THREAD

**Issue by relife957** [zxh0/jvmgo-book#41]
试了文中三种方法,都不能识别jre路径,想问下有没有人有解法

**Comment by LinZhanMing** [comment]
需要安装 jre, https://java.com/zh-CN/download/
安装位置在 /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home

### entry_zip.go
```go
import "runtime"
...
func (self *ZipEntry) readClass(className string) ([]byte, Entry, error)  {
    ...
    defer r.Close()

    // 判断是 macos
    if runtime.GOOS == "darwin" {
         // java.lang.Object.class --> java/lang/Object.class
	 packagePoint := strings.Count(className, ".") - 1
	 className = strings.Replace(className, ".", "/", packagePoint)
    }

    for _, f := range reader.File { ... }
}
```

<img width="1237" alt="image" src="https://user-images.githubusercontent.com/60056876/167287976-60613022-b544-409a-8da4-1b2adca3efc1.png">
