### ISSUE TITLE
书中第七章发现错误

### ISSUE THREAD

**Issue by MisterChangRay** [zxh0/jvmgo-book#42]
第七章中 , 下段文本发现错误
 
原文如下:
=======================================================
parseMethodDescriptor（）函数分解方法描述符，返回一个
MethodDescriptor结构体实例。这个结构体定义在
ch06\rtda\heap\method_descriptor.go文件中，代码如下：
=======================================================
其中 method_descriptor.go 此文件应在 ch07\rtda\heap\method_descriptor.go 路径中

**Comment by zxh0** [comment]
收到，感谢提供反馈👍
