### ISSUE TITLE
Init java.lang.Object Multi Times

### ISSUE THREAD

**Issue by eleree** [zxh0/jvmgo-book#6]
![jvm1](https://cloud.githubusercontent.com/assets/2663692/20701450/05c1fa56-b64e-11e6-9110-441ffd78116c.png)
![jvm2](https://cloud.githubusercontent.com/assets/2663692/20701453/06d7231c-b64e-11e6-8923-44d259f06601.png)

**Comment by zxh0** [comment]
应该是`GetClinitMethod()`方法的bug，这个方法会返回超类里的`<clinit>`方法。

**Comment by zxh0** [comment]
已经fix了
