### ISSUE TITLE
ch11.exe not support higer jre like jre1.8.0_77

### ISSUE THREAD

**Issue by eleree** [zxh0/jvmgo-book#7]
![higer_jre](https://cloud.githubusercontent.com/assets/2663692/20779170/b42744a6-b7ad-11e6-8a9e-001c59e59094.png)

**Comment by zxh0** [comment]
原因是`AtomicLong`多了一个`VMSupportsCS8()`本地方法，需要实现。

**Comment by zxh0** [comment]
已经fix
